// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	admin "ms_tmdb/internal/handler/admin"
	"ms_tmdb/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/auto-sync",
				Handler: admin.GetAutoSyncSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/auto-sync",
				Handler: admin.UpdateAutoSyncSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/auto-sync/logs",
				Handler: admin.ListAutoSyncLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/auto-sync/logs",
				Handler: admin.ClearAutoSyncLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/auto-sync/logs/:id",
				Handler: admin.GetAutoSyncLogDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auto-sync/run",
				Handler: admin.RunAutoSyncNowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/compare/movie/:id",
				Handler: admin.CompareMovieRemoteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/compare/person/:id",
				Handler: admin.ComparePersonRemoteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/compare/tv/:id",
				Handler: admin.CompareTvRemoteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/home",
				Handler: admin.GetHomeDashboardHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/logs/access",
				Handler: admin.ListProxyAccessLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/logs/access",
				Handler: admin.ClearProxyAccessLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/logs/access/:id",
				Handler: admin.GetProxyAccessLogDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/logs/tmdb",
				Handler: admin.ListTmdbRequestLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/logs/tmdb",
				Handler: admin.ClearTmdbRequestLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/logs/tmdb/:id",
				Handler: admin.GetTmdbRequestLogDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/movie",
				Handler: admin.CreateMovieHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/movie/:id",
				Handler: admin.DeleteMovieHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/movie/:id",
				Handler: admin.UpdateMovieHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/movie/:id/local",
				Handler: admin.ClearMovieLocalHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/movies",
				Handler: admin.ListMoviesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/proxy",
				Handler: admin.GetProxySettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/proxy",
				Handler: admin.UpdateProxySettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync/movie/:id",
				Handler: admin.SyncMovieHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync/person/:id",
				Handler: admin.SyncPersonHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sync/tv/:id",
				Handler: admin.SyncTvSeriesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tv",
				Handler: admin.CreateTvSeriesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv-series",
				Handler: admin.ListTvSeriesHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/tv/:id",
				Handler: admin.DeleteTvSeriesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tv/:id",
				Handler: admin.UpdateTvSeriesHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/tv/:id/local",
				Handler: admin.ClearTvSeriesLocalHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/tv/:id/season/:season_number/local",
				Handler: admin.GetTvSeasonLocalHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tv/:id/season/:season_number/local",
				Handler: admin.SaveTvSeasonLocalHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/tv/:id/season/:season_number/local",
				Handler: admin.UpdateTvSeasonLocalHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/tv/:id/season/:season_number/local",
				Handler: admin.DeleteTvSeasonLocalHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload/image",
				Handler: admin.UploadImageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/admin"),
	)
}
